#App info

name: telehealth
description: Telehealth Flutter app
####################################################################################################


#Environment Config

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


####################################################################################################

dependencies:
  flutter:
    sdk: flutter

  # Widgets
  cupertino_icons: ^0.1.2

  #Network
  http: ^0.12.0+1
  url_launcher: ^5.1.2
  #chopper: ^3.0.0
  amazon_cognito_identity_dart: ^0.0.22

  # System
  permission_handler: ^3.2.2
  file_picker: ^1.3.8

  # Persistence
  shared_preferences: ^0.5.3+4
  floor: ^0.9.0


  # Architecture Components
  rxdart: ^0.18.0
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject


####################################################################################################


#dependency_overrides:
#  analyzer: ^0.38.2

####################################################################################################


dev_dependencies:

  #Testing
  flutter_test:
    sdk: flutter

  # Code Generators
  build_runner: ^1.0.0
  #chopper_generator: ^3.0.0 #will have to try build runner with this library
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator


####################################################################################################


# Default design language
flutter:
  uses-material-design: true

####################################################################################################


# Assets and Resources
fonts:
  - family:  TelehealthIcons
    fonts:
      - asset: fonts/TelehealthIcons.ttf
