#App info

name: telehealth
description: Telehealth Flutter app
####################################################################################################


#Environment Config

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


####################################################################################################

dependencies:
  flutter:
    sdk: flutter

  # Widgets
  cupertino_icons: ^0.1.2

  #Network
  http: ^0.12.0+1


  # Architecture Components
  rxdart: ^0.18.0
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject


####################################################################################################


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generators
  build_runner: ^1.0.0
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator


####################################################################################################


# Default design language
flutter:
  uses-material-design: true

####################################################################################################


# Assets and Resources
fonts:
  - family:  TelehealthIcons
    fonts:
      - asset: fonts/TelehealthIcons.ttf
